### ISSUE TITLE
maybe clear the path after terminal has opened ?

### ISSUE THREAD

**Issue by ctf0** [randy3k/OpenHere#2]
atm its 
```bash
$ cd /a/b/c
$ /a/b/c> |
```
but with clear, the terminal should be
```bash
$ /a/b/c> |
```

**Comment by randy3k** [comment]
Are you using iterm? Try the beta version, it fixes this issue.

**Comment by ctf0** [comment]
got it , thanx, btw is there an option to open terminal at the project root instead of the current file path ?

**Comment by randy3k** [comment]
For now, just open a plain new file and launch the command.

**Comment by ctf0** [comment]
yeah i figured, thanx
